lgeneral: consistent indentation

diff --git a/supported/lgeneral b/supported/lgeneral
--- a/supported/lgeneral
+++ b/supported/lgeneral
@@ -6,8 +6,8 @@ LONGNAME="LGeneral"
 TGZSUM=40c4be23f60d1dc732aabe13b58fc5e3
 
 lgeneral_usage() {
-	echo "game-data-packager ${SHORTNAME} arguments:"
-	printf "\tgame-data-packager ${SHORTNAME} [ -f path ] | [ -w ]
+    echo "game-data-packager ${SHORTNAME} arguments:"
+    printf "\tgame-data-packager ${SHORTNAME} [ -f path ] | [ -w ]
 \t\t-f file\t\tpath to your tar.gz compressed Panzer General DAT directory\n\
 \t\t-w\t\tfetch compressed pg-data.tar.gz from the web\n"
 }
@@ -20,9 +20,9 @@ verify_args() {
             ;;
         1)
             if [ "$1" != "-w" ]; then
-                    usage >&2
-                    lgeneral_usage >&2
-                    exit 1
+                usage >&2
+                lgeneral_usage >&2
+                exit 1
             fi
             downloadtgz
             ;;
@@ -63,48 +63,44 @@ DEBBASE="lgeneral-data-nonfree_${GAME_PACKAGE_VERSION}_all.deb"
 DEB="$DATADIR/$DEBBASE"
 
 go() {
-	verify_args "$@"
-	TGZFILE=`unravel "$lgeneraltgz"`
+    verify_args "$@"
+    TGZFILE=`unravel "$lgeneraltgz"`
 
-	verify_file "$TGZFILE"
-    	[ -r "$TGZFILE" ] || die "ERROR: '$TGZFILE' cannot be read."
+    verify_file "$TGZFILE"
+    [ -r "$TGZFILE" ] || die "ERROR: '$TGZFILE' cannot be read."
 
-	verify_md5sum_alternatives "$TGZFILE" "$TGZSUM" \
-		"warning: checksum is not what we expected"
+    verify_md5sum_alternatives "$TGZFILE" "$TGZSUM" \
+        "warning: checksum is not what we expected"
 
-    	OUTFILE=`unravel "$OUTDIR"`"/$DEBBASE"
+    OUTFILE=`unravel "$OUTDIR"`"/$DEBBASE"
+    cp -p "$DEB" "$OUTFILE"
+    oldpwd=`pwd`
+    cd "$WORKDIR"
 
-	cp -p "$DEB" "$OUTFILE"
+    # create directory structure required by lgc-pg
+    mkdir -p lgeneral/gfx/flags \
+             lgeneral/gfx/terrain \
+             lgeneral/gfx/units \
+             lgeneral/maps/pg \
+             lgeneral/nations \
+             lgeneral/scenarios/pg \
+             lgeneral/sounds/pg \
+             lgeneral/units
 
-	oldpwd=`pwd`
-
-	cd "$WORKDIR"
-
-	# create directory structure required by lgc-pg
-	mkdir -p lgeneral/gfx/flags \
-	         lgeneral/gfx/terrain \
-	         lgeneral/gfx/units \
-	         lgeneral/maps/pg \
-	         lgeneral/nations \
-	         lgeneral/scenarios/pg \
-	         lgeneral/sounds/pg \
-	         lgeneral/units
-
-	# extract pg-data and convert to lgeneral's native file format
-    	tar xfz "$TGZFILE"
-    	lgc-pg -s pg-data/ -d lgeneral/
-	
-	
-    	slipstream_dir "$OUTFILE" "usr/share/games/" "lgeneral/"
+    # extract pg-data and convert to lgeneral's native file format
+    tar xfz "$TGZFILE"
+    lgc-pg -s pg-data/ -d lgeneral/
+    
+    slipstream_dir "$OUTFILE" "usr/share/games/" "lgeneral/"
 
     if [ "$downloaded" = "true" ]; then
         rm "$TGZFILE"
-	rm -rf pg-data/
-	rm -rf lgeneral/
+        rm -rf pg-data/
+        rm -rf lgeneral/
     elif [ "$downloaded" = "false" ]; then
-	rm -rf pg-data/
-	rm -rf lgeneral/
+        rm -rf pg-data/
+        rm -rf lgeneral/
     fi
 
-	cd "$oldpwd"
+    cd "$oldpwd"
 }
